version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - "db"
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: "python ./main.py"

  db:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT_EXT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
    - "db:/var/lib/postgresql/data"

volumes:
  db: {}
