version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - "db"
    env_file:
      - .env
    command: "python ./main.py"
    networks:
      - nginx-load-balancer
      - internal
    restart: always

  webpack:
    build:
      context: "."
      dockerfile: "Dockerfile-webpack"
    volumes:
      - .:/app
    networks:
      - internal
    # Use this to keep the container running
    tty: true
    restart: always

  db:
    image: "postgres:13-alpine"
    volumes:
      - "db:/var/lib/postgresql/data"
      - "./postgres-dev-init.sh:/docker-entrypoint-initdb.d/postgres-dev.init.sh"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB},${POSTGRES_DB}_test
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - internal
    restart: always

volumes:
  db: {}

networks:
  internal:
  nginx-load-balancer:
    name: docker_nginx-load-balancer
    external: true
