"""Add rechtspraak_internal_id to person

This is a large migration. We used to believe that the toon_naam of every preson is unique:
it is not. Hence we drop the unique constraint on that column. We now use the internal
rechtspraak ID for every person.

This migration contains four parts:
1. Add new column: rechtspraak_internal_id.
2. Populate the column for every person.
3. Deduplicate people base on the new internal id.
4. Remove unique constraint on toon_naam and add it to rechtspraak_internal_id.

 Instead we extract the
internal rechtspraak id from each judge, deduplicate people based on that, and then add
a unique constraint on that new column.


Revision ID: 14a4c9f6fa39
Revises: 41fe8ef5e03f
Create Date: 2026-05-01 13:30:28.899548

"""
from alembic import op
from flask import current_app
import sqlalchemy as sa
from sqlalchemy.orm import Session, sessionmaker

from app.extensions import db
from app.models import Person, PersonVerdict, Verdict


# revision identifiers, used by Alembic.
revision = '14a4c9f6fa39'
down_revision = '41fe8ef5e03f'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1. Add new column: rechtspraak_internal_id.
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rechtspraak_internal_id', sa.Text()))

    # Step 2. Populate the column for every person.
    session = Session(bind=op.get_bind())
    people = session.query(Person).filter(Person.rechtspraak_internal_id.is_(None)).all()
    for person in people:
        if not person.rechtspraak_id:
            raise ValueError(f"Person '{person.id}' has no rechtspraak_id")
        internal_id = Person.extract_rechtspraak_internal_id(person.rechtspraak_id)
        person.rechtspraak_internal_id = internal_id
        session.add(person)
    session.commit()

    # Step 3. Deduplicate people base on the new internal id.
    people = session.query(Person).all()

    for i, person in enumerate(people):
        if i % 250 == 0:
            print(f"Deduplicating {i} / {len(people)}")
        identical_people = session.query(Person).filter(Person.rechtspraak_internal_id == person.rechtspraak_internal_id).all()

        # Just one person with the same internal id: great!
        if len(identical_people) == 1:
            continue

        # Deduplication works in three steps:
        # 1. Find the person that was most recently added; we assume that person is correct
        # 2. Move the verdicts of the old person to the new person
        #    Note: We don't merge side jobs and professional details: we assume that the most recent information is correct
        # 3. Add redirection from old person to new person

        # Find the newest person
        newest = identical_people[0]
        for person in identical_people:
            if person.created_at >= newest.created_at:
                newest = person
        identical_people.remove(newest)

        # Merge verdicts
        verdict_ids = [v.verdict_id for v in newest.verdicts]
        for person in identical_people:
            for verdict in person.verdicts:
                if verdict.id not in verdict_ids:
                    verdict.person_id = newest.id
                    session.add(verdict)
            session.commit()

        # Delete the old people
        for person in identical_people:
            for pd in person.professional_detail:
                session.delete(pd)
            for sj in person.side_job:
                session.delete(sj)
            session.delete(person)
            session.commit()

    # Step 4. Remove unique constraint on toon_naam and add it to rechtspraak_internal_id.
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('person_toon_naam_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['rechtspraak_internal_id'])
        batch_op.alter_column('rechtspraak_internal_id', existing_type=sa.TEXT(), nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['toon_naam'])
        batch_op.drop_column('rechtspraak_internal_id')

    # ### end Alembic commands ###
