"""Add side jobs

Revision ID: 1bb142d520d1
Revises: bbbafc44e4a0
Create Date: 2021-02-06 21:08:10.072893

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1bb142d520d1"
down_revision = "bbbafc44e4a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "side_jobs",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("function", sa.Text(), nullable=False),
        sa.Column("place", sa.Text(), nullable=True),
        sa.Column("paid", sa.Text(), nullable=True),
        sa.Column("organisation_name", sa.Text(), nullable=True),
        sa.Column("organisation_type", sa.Text(), nullable=True),
        sa.Column("person_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("side_jobs")
    # ### end Alembic commands ###
