"""Add protected col to people table

Revision ID: 21664ed1fba0
Revises: ed7900496edb
Create Date: 2021-02-06 21:46:35.623193

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21664ed1fba0"
down_revision = "ed7900496edb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("people", sa.Column("protected", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("people", "protected")
    # ### end Alembic commands ###
