"""add indexes and beslissings text

Revision ID: 24d67ed9a5ec
Revises: ac70777048af
Create Date: 2021-02-28 12:31:05.101647

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "24d67ed9a5ec"
down_revision = "ac70777048af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "institution", ["lido_id"])
    op.create_unique_constraint(None, "legal_area", ["legal_area_lido_id"])
    op.create_unique_constraint(None, "procedure_type", ["lido_id"])
    op.add_column("verdict", sa.Column("beslissings_text", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verdict", "beslissings_text")
    op.drop_constraint(None, "procedure_type", type_="unique")
    op.drop_constraint(None, "legal_area", type_="unique")
    op.drop_constraint(None, "institution", type_="unique")
    # ### end Alembic commands ###
