"""Deduplicate_people_based_on_toon_naam

Revision ID: 2684f0161ed5
Revises: 14a4c9f6fa39
Create Date: 2026-05-01 15:05:09.459986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from app.models import Person


# revision identifiers, used by Alembic.
revision = '2684f0161ed5'
down_revision = '14a4c9f6fa39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())

    # These IDs are related to a toon_naam for which multiple people exist.
    # We drop their side jobs and professional details, because these were
    # merged from two people to one person. That is clearly wrong.
    # Commit d8fcef077719dcde59ca1ea516bd353ef54c6beb fixes this.
    # This migration cleans old database artefacts.
    ids_to_clean = [
        "875b0ae3-f8e5-4ca4-b859-7deaf568a0a9",
        "9b289808-30ad-4b0c-af76-7b0dbdede72c",
        "b025cc63-553a-4a19-a8f5-84688b07d9aa",
        "c12794fa-e97f-4f93-aa35-18f9395fbf38",
    ]

    for id_ in ids_to_clean:
        person = session.query(Person).filter(Person.id == id_).first()

        for pd in person.professional_detail:
            session.delete(pd)
        for sj in person.side_job:
            session.delete(sj)
        session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        pass
    # ### end Alembic commands ###
