"""add boolean to indicate if verdict contains decision text

Revision ID: 2cd20c4772b8
Revises: c44e62526dd5
Create Date: 2021-02-16 21:11:29.291103

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2cd20c4772b8"
down_revision = "c44e62526dd5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verdict",
        sa.Column(
            "contains_beslissing", sa.Boolean(), nullable=False, server_default="False"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verdict", "contains_beslissing")
    # ### end Alembic commands ###
