"""Add first_scraped_at to Person

Revision ID: 2f402885e9a0
Revises: 609daae4bb63
Create Date: 2026-04-26 13:01:47.997107

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f402885e9a0'
down_revision = '609daae4bb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_scraped_at', sa.DateTime()))

    with op.batch_alter_table('person', schema=None) as batch_op:
        conn = op.get_bind()
        conn.execute(sa.text("UPDATE person SET first_scraped_at = NOW() WHERE first_scraped_at IS NULL;"))
        batch_op.alter_column("first_scraped_at", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('first_scraped_at')

    # ### end Alembic commands ###
