"""Add outside_of_judiciary  to professional detail

Revision ID: 30093f73cee6
Revises: 2684f0161ed5
Create Date: 2026-05-02 17:22:23.963233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from app.models import Person, ProfessionalDetail


# revision identifiers, used by Alembic.
revision = '30093f73cee6'
down_revision = '2684f0161ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outside_of_judiciary', sa.Boolean(), nullable=True))

    session = Session(bind=op.get_bind())
    professional_details = session.query(ProfessionalDetail).all()
    for pd in professional_details:
        pd.outside_of_judiciary = False
        session.add(pd)
    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_detail', schema=None) as batch_op:
        batch_op.drop_column('outside_of_judiciary')

    # ### end Alembic commands ###
