"""Remove unused first_name column

Revision ID: 41fe8ef5e03f
Revises: e92e1d819a59
Create Date: 2026-05-01 11:43:36.323972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fe8ef5e03f'
down_revision = 'e92e1d819a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
