"""add procedure type to verdicts

Revision ID: 4398781f5075
Revises: 1b58fb814157
Create Date: 2021-02-27 19:42:43.615387

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4398781f5075"
down_revision = "1b58fb814157"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "procedure_type", ["id"])
    op.add_column(
        "verdict",
        sa.Column("procedure_type_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        None, "verdict", "procedure_type", ["procedure_type_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "verdict", type_="foreignkey")
    op.drop_column("verdict", "procedure_type_id")
    op.drop_constraint(None, "procedure_type", type_="unique")
    # ### end Alembic commands ###
