"""add institution to verdicts

Revision ID: 577a3c2d519a
Revises: 6118877635f1
Create Date: 2021-02-27 19:25:49.616363

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "577a3c2d519a"
down_revision = "6118877635f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verdict",
        sa.Column("institution_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(None, "verdict", "institution", ["institution_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "verdict", type_="foreignkey")
    op.drop_column("verdict", "institution_id")
    # ### end Alembic commands ###
