"""Drop unused deep-link url

Revision ID: 609daae4bb63
Revises: ee55d66a1516
Create Date: 2023-05-21 10:26:30.991369

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "609daae4bb63"
down_revision = "ee55d66a1516"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("verdict", schema=None) as batch_op:
        batch_op.drop_column("deep_link")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("verdict", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deep_link", sa.TEXT(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
