"""Add persoon_id from rechtspraak

Revision ID: 6472e29d7a3b
Revises: 079b24fff309
Create Date: 2021-02-06 15:02:39.395993

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6472e29d7a3b"
down_revision = "079b24fff309"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("people", sa.Column("rechtspraak_id", sa.Text(), nullable=False))
    op.create_unique_constraint(None, "people", ["rechtspraak_id"])
    op.create_unique_constraint(None, "people", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "people", type_="unique")
    op.drop_constraint(None, "people", type_="unique")
    op.drop_column("people", "rechtspraak_id")
    # ### end Alembic commands ###
