"""Deduplicate people based on toon_naam

Revision ID: 8c7760be77d8
Revises: b1b751b52d7f
Create Date: 2026-08-10 18:45:53.918670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from app.models import Person


# revision identifiers, used by Alembic.
revision = '8c7760be77d8'
down_revision = 'b1b751b52d7f'
branch_labels = None
depends_on = None


def upgrade():
    """
    This migration deduplicates people. This deduplication in necessary because after the
    deployment of the new nevenfunctieregister of rechtspraak.nl, there was no unique ID to
    link people from the old register to people in the new register.

    It works in two steps:
    1. We first deduplicated a few people by hand. These people had identical names, i.e. O. Nijhuis.
       We matched these new and old people by hand. We copy their new identifier to their old profile.
    2. The remaining people are matched automatically. We strip the gender pronoun of the old person and
       match purely by name.

       We select old people by querying the length of the rechtspraak_id. In the old register, this
       id was 32 characters long. In the new register this length is 36.

       We subsequently delete the new person.

    We want to keep the old person because:
    1. Search engines and websites link to old people.
    2. Old side jobs / professional details are included on their profile.
    3. Hundreds of thousands of verdicts are linked to these people.
    """
    session = Session(bind=op.get_bind())

    manual_deduplicated = [
        {"old": "875b0ae3-f8e5-4ca4-b859-7deaf568a0a9", "new": "1dc9c54d-6c02-45b1-b0fb-401f4a9d209b"},
        {"old": "3c38e8f6-f7fa-4bdb-af59-60af910942b4", "new": "4fd9d766-c325-4de9-93fc-03ab7fff9479"},
        {"old": "b39f3ea0-3e3a-4fd6-8976-c5279d10ab9a", "new": "fd2e974d-958f-4b63-bc59-89f60e4bb4a5"},
        {"old": "1276327c-1935-4f2b-87e0-d9ac30ccc11a", "new": "4e5728c6-69a5-4bf9-8356-8498e56c90c5"},
        {"old": "c12794fa-e97f-4f93-aa35-18f9395fbf38", "new": "9bced5bc-a602-4291-9c8f-2e3a007708f5"},
        {"old": "9b289808-30ad-4b0c-af76-7b0dbdede72c", "new": "527d21ff-c175-4f91-9dc9-0f95d46a38d5"},
        {"old": "652c9351-1fb4-431d-86f2-dff482e4360c", "new": "693ac68e-bb9e-46a2-b6ec-6d39f4236edd"},
        {"old": "766e1cc6-60d8-42a3-ad2d-2d779ca93fbd", "new": "1ca46cfd-50f9-4b14-8216-56882affa9e3"},
        {"old": "b025cc63-553a-4a19-a8f5-84688b07d9aa", "new": "0ff17317-7b1d-4cb9-a2c3-beabe738d87b"},
        {"old": "9fe22cac-5624-4d58-8e69-484efde1c65a", "new": "21247713-6a57-4030-b65f-b929a1a23644"},
        {"old": "7574e63e-dd0c-4df6-99d0-93c457feec92", "new": "1c944d9c-8435-45f3-8b99-dfd462bb2b1f"},
        {"old": "e28a50b4-afba-42fc-9ef1-25bcb49876f8", "new": "e1c455ac-4127-4d16-902c-adc22243668c"},
        {"old": "e1c990c6-a538-42d7-b60b-47c4ad2d649c", "new": "57e832c7-9d1a-46fe-8bc7-cdc4ccba231b"},
    ]

    for item in manual_deduplicated:
        new_person = session.query(Person).filter(Person.id == item.get("new")).first()
        if not new_person:
            continue

        new_rechtspraak_id = new_person.rechtspraak_id

        for pd in new_person.professional_detail:
            session.delete(pd)
        for sj in new_person.side_job:
            session.delete(sj)

        session.delete(new_person)
        session.commit()

        old_person = session.query(Person).filter(Person.id == item.get("old")).first()
        old_person.rechtspraak_id = new_rechtspraak_id
        session.add(old_person)
        session.commit()

    # Step 2: automatic deduplication
    rechtspraak_id_length = 32
    old_people = session.query(Person).filter(sa.func.length(Person.rechtspraak_id) == rechtspraak_id_length)
    count = old_people.count()

    for i, old_person in enumerate(old_people.all()):
        print(f"{i} / {count}", end="\r")

        name = old_person.toon_naam.replace("dhr.", "").replace("mw.", "").strip()
        new_match = session.query(Person).filter(Person.toon_naam == name).all()

        if len(new_match) > 1:
            raise ValueError(f"Expected {old_person.toon_naam} to have only one match, but found {len(new_match)}. Deduplicate this person yourself and then run the migration again.")
        elif len(new_match) == 0:
            continue

        new_match = new_match[0]
        new_rechtspraak_id = new_match.rechtspraak_id

        # Delete the new person
        for pd in new_match.professional_detail:
            session.delete(pd)
        for sj in new_match.side_job:
            session.delete(sj)

        session.delete(new_match)
        session.commit()

        old_person.rechtspraak_id = new_rechtspraak_id
        session.add(old_person)
        session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
