"""add legal area to verdicts

Revision ID: ac70777048af
Revises: fb362d4ec3bd
Create Date: 2021-02-27 23:14:26.005128

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ac70777048af"
down_revision = "fb362d4ec3bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "legal_area", ["id"])
    op.add_column(
        "verdict",
        sa.Column("legal_area_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(None, "verdict", "legal_area", ["legal_area_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "verdict", type_="foreignkey")
    op.drop_column("verdict", "legal_area_id")
    op.drop_constraint(None, "legal_area", type_="unique")
    # ### end Alembic commands ###
