"""Drop main_job column for professional detail

Revision ID: b1b751b52d7f
Revises: b6ea9011b5e8
Create Date: 2026-08-02 11:04:26.454486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b751b52d7f'
down_revision = 'b6ea9011b5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_detail', schema=None) as batch_op:
        batch_op.drop_column('main_job')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_job', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
