"""Drop various columns not exposed by rechtspraa

Revision ID: b6ea9011b5e8
Revises: c1f9d8e1aac3
Create Date: 2026-08-02 09:20:53.739947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ea9011b5e8'
down_revision = 'c1f9d8e1aac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('last_name_partner')
        batch_op.drop_column('last_name_own')
        batch_op.drop_column('toon_naam_kort')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toon_naam_kort', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name_own', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name_partner', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
