"""fix

Revision ID: b8493137763b
Revises: d2a7e43068dd
Create Date: 2021-02-27 19:04:13.286001

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b8493137763b"
down_revision = "d2a7e43068dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("institution", "type", existing_type=sa.TEXT(), nullable=False)
    op.create_unique_constraint(None, "institution", ["id"])
    op.create_unique_constraint(None, "person", ["id"])
    op.create_unique_constraint(None, "person_verdict", ["id"])
    op.create_unique_constraint(None, "professional_detail", ["id"])
    op.create_unique_constraint(None, "side_job", ["id"])
    op.create_unique_constraint(None, "verdict", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "verdict", type_="unique")
    op.drop_constraint(None, "side_job", type_="unique")
    op.drop_constraint(None, "professional_detail", type_="unique")
    op.drop_constraint(None, "person_verdict", type_="unique")
    op.drop_constraint(None, "person", type_="unique")
    op.drop_constraint(None, "institution", type_="unique")
    op.alter_column("institution", "type", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
