"""Add last scraped at for person

Revision ID: bbbafc44e4a0
Revises: 9608dea2653e
Create Date: 2021-02-06 19:44:45.128965

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bbbafc44e4a0"
down_revision = "9608dea2653e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("people", sa.Column("last_scraped_at", sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, "professional_details", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "professional_details", type_="unique")
    op.drop_column("people", "last_scraped_at")
    # ### end Alembic commands ###
