"""Drop rechtspraak_internal_id

Revision ID: c1f9d8e1aac3
Revises: 30093f73cee6
Create Date: 2026-08-02 08:15:18.650548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f9d8e1aac3'
down_revision = '30093f73cee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('person_rechtspraak_internal_id_key'), type_='unique')
        batch_op.drop_column('rechtspraak_internal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rechtspraak_internal_id', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('person_rechtspraak_internal_id_key'), ['rechtspraak_internal_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
