"""Add organisation to professional details

Revision ID: c3fd9c59c492
Revises: 21664ed1fba0
Create Date: 2021-02-06 22:48:27.013696

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c3fd9c59c492"
down_revision = "21664ed1fba0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "professional_details", sa.Column("organisation", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("professional_details", "organisation")
    # ### end Alembic commands ###
