"""Add location to professional detail

Revision ID: d6e38fddc8c0
Revises: 2684f0161ed5
Create Date: 2026-05-02 18:49:22.514275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e38fddc8c0'
down_revision = '2684f0161ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_detail', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
