"""Add extra columns to Person model

Revision ID: e92e1d819a59
Revises: 2f402885e9a0
Create Date: 2026-05-01 07:18:21.894806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92e1d819a59'
down_revision = '2f402885e9a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name_own', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_name_partner', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('did_not_self_report_side_jobs', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_no_side_jobs', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('has_no_side_jobs')
        batch_op.drop_column('did_not_self_report_side_jobs')
        batch_op.drop_column('last_name_partner')
        batch_op.drop_column('last_name_own')

    # ### end Alembic commands ###
