"""Deprecate historical col on professional details table

Revision ID: ed7900496edb
Revises: 1bb142d520d1
Create Date: 2021-02-06 21:43:20.613470

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ed7900496edb"
down_revision = "1bb142d520d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("professional_details", "historical")
    op.create_unique_constraint(None, "side_jobs", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "side_jobs", type_="unique")
    op.add_column(
        "professional_details",
        sa.Column("historical", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
