"""unique toonnaam

Revision ID: f2e19ac382a2
Revises: b53f3c980d29
Create Date: 2021-02-06 15:28:41.082850

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "f2e19ac382a2"
down_revision = "b53f3c980d29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "people", ["toon_naam"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "people", type_="unique")
    # ### end Alembic commands ###
